apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-feed
  labels:
    app: backend-feed
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend-feed
  template:
    metadata:
      name: backend-feed
      labels:
        app: backend-feed
    spec:
      volumes:
        - name: aws-secret
          secret:
            secretName: aws-secret
      containers:
      - name: udagram-api-feed
        image: adaugo/udagram-api-feed:v3
        imagePullPolicy: Always
        volumeMounts:
          - name: aws-secret
            mountPath: "/root/.aws/"
            readOnly: true
        resources:
          limits:
            cpu: 500m
          requests:
            cpu: 200m
        env:
        - name: URL
          valueFrom:
            configMapKeyRef:
              name: env-config
              key: URL
        - name: AWS_BUCKET
          valueFrom:
            configMapKeyRef:
              name: env-config
              key: AWS_BUCKET
        - name: AWS_PROFILE
          valueFrom:
            configMapKeyRef:
              name: env-config
              key: AWS_PROFILE
        - name: AWS_REGION
          valueFrom:
            configMapKeyRef:
              name: env-config
              key: AWS_REGION
        - name: JWT_SECRET
          valueFrom:
            configMapKeyRef:
              name: env-config
              key: JWT_SECRET
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: env-config
              key: POSTGRES_DB
        - name: POSTGRES_HOST
          valueFrom:
            configMapKeyRef:
              name: env-config
              key: POSTGRES_HOST
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: env-secret
              key: POSTGRES_PASSWORD
        - name: POSTGRES_USERNAME
          valueFrom:
            secretKeyRef:
              name: env-secret
              key: POSTGRES_USERNAME
        ports:
        - containerPort: 8080
      restartPolicy: Always


---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: backend-feed
  name: backend-feed
spec:
  ports:
  - name: "8080"
    port: 8080
    protocol: TCP
  selector:
    app: backend-feed