apiVersion: apps/v1
kind: Deployment
metadata:
  name: reverseproxy
  labels: 
    app: reverseproxy
spec:
  selector:
    matchLabels:
      app: reverseproxy
  replicas: 1
  template:
    metadata:
      name: reverseproxy
      labels:
        app: reverseproxy
    spec:
      containers:
      - name: reverseproxy
        image: adaugo/reverseproxy:v3
        imagePullPolicy: Always
        resources:
          limits:
            cpu: "500m"
          requests:
            cpu: "200m"
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: reverseproxy
  name: reverseproxy
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  selector:
    app: reverseproxy